version: "3.7"
services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - {{Slug}}

  api:
    image: node:14
    volumes:
      - ${API_PATH}:/usr/src/app:cached
    working_dir: /usr/src/app
    expose:
      - ${API_PORT}
    depends_on:
      - data
    container_name: ${API_HOST}
    environment:
      - VIRTUAL_HOST=${API_HOST}
    env_file:
      - .env
    networks:
      - {{Slug}}
    command: ["npm", "run", "start:dev"]

  app:
    image: node:14
    volumes:
      - ${APP_PATH}:/usr/src/app:cached
    working_dir: /usr/src/app
    expose:
      - ${APP_PORT}
    depends_on:
      - api
    container_name: ${APP_HOST}
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - VIRTUAL_PORT=${APP_PORT}
      - VUE_APP_API_HOST=${API_HOST}
    networks:
      - {{Slug}}
    command: ["npm", "run", "serve"]

  data:
    image: node:14
    volumes:
      - ${DATA_PATH}:/usr/src/app:cached
    working_dir: /usr/src/app
    expose:
      - ${DATA_PORT}
    depends_on:
      - postgres
    container_name: ${DATA_HOST}
    env_file:
      - .env
    networks:
      - {{Slug}}
    command: ["npm", "run", "start:dev"]

  postgres:
    image: postgres:11-alpine
    env_file:
      - .env
    container_name: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - {{Slug}}
    volumes:
      - {{Slug}}-data:/var/lib/postgresql/data:cached

volumes:
  {{Slug}}-data:

networks:
  {{Slug}}:
